=== DmitryGontarenko/usefultricks/jsonxml/src/main/resources/xml/schema.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="https://www.w3schools.com"
           xmlns="https://www.w3schools.com"
           elementFormDefault="qualified">

    <xs:element name="person">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="employee" type="fullpersoninfo"/>
                <xs:element name="planet" type="xs:string" default="earth"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="fullpersoninfo">
        <xs:complexContent>
            <xs:extension base="personinfo">
                <xs:sequence>
                    <xs:element name="home">
                        <xs:complexType>
                            <xs:sequence>
                                <xs:element name="country" type="xs:string"/>
                                <xs:element name="city" type="xs:string"/>
                                <xs:element name="street" type="xs:string"/>
                            </xs:sequence>
                        </xs:complexType>
                    </xs:element>
                </xs:sequence>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="personinfo">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="phone" type="xs:string" maxOccurs="3"/>
            <xs:element name="age" type="xs:positiveInteger"/>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string"/>
    </xs:complexType>

</xs:schema>

=== DmitryGontarenko/usefultricks/src/main/resources/xml/house.xml
<?xml version="1.0"?>
<person xmlns="https://www.w3schools.com"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="https://www.w3schools.com schema.xsd">

    <employee id="1">
        <name>Tony</name>
        <phone>357790</phone>
        <phone>124903</phone>
        <age>23</age>
        <home>
            <country>Russia</country>
            <city>Moscow</city>
            <street>Main-street, 4</street>
        </home>
    </employee>
    <planet>Earth</planet>
</person>
